package routing

import (
	"encoding/json"
	"os"
	"path/filepath"
	"time"
)

// CompiledRoutingVersion is the schema version of routing.json. Bump on a
// breaking change to the shape the sandbox reads.
const CompiledRoutingVersion = 1

// CompiledRoute is one resolved intent the sandbox consumes: the chosen model
// plus the rationale (kept for auditability — the sandbox only needs Model).
type CompiledRoute struct {
	Model          string  `json:"model"`
	TaskType       string  `json:"task_type"`
	Objective      string  `json:"objective"`
	ConstraintsMet bool    `json:"constraints_met"`
	Accuracy       float64 `json:"accuracy,omitempty"`
	CostUSD        float64 `json:"cost_usd,omitempty"`
	LatencyMs      float64 `json:"latency_ms,omitempty"`
	Reason         string  `json:"reason"`
}

// CompiledRouting is the file the sandbox reads (routing.json). It maps intent
// name -> resolved route. It is generated by `route compile`; the sandbox never
// runs the resolver itself (single source of truth on the host) and never calls
// the host at spawn time (no hang risk).
type CompiledRouting struct {
	Version         int                      `json:"version"`
	Generated       string                   `json:"generated"`
	Note            string                   `json:"note"`
	DefaultFallback string                   `json:"default_fallback"`
	Routes          map[string]CompiledRoute `json:"routes"`
}

const compiledNote = "Generated by `pi-stack route compile`. Maps an agent/task INTENT to the model the resolver chose from the current registry + scorecard. The sandbox (subagents.ts) reads routes[intent].model. Do not hand-edit — re-run compile after changing models.json / scorecard.json / policy.json (scorecard.json is hand-maintained; edit it directly, then re-run compile)."

// Compile resolves every intent in the policy and returns the routing.json
// payload. now is injected so the output is reproducible in tests.
func Compile(reg *Registry, sc *Scorecard, pol *Policy, now time.Time) CompiledRouting {
	out := CompiledRouting{
		Version:         CompiledRoutingVersion,
		Generated:       now.UTC().Format(time.RFC3339),
		Note:            compiledNote,
		DefaultFallback: pol.DefaultFallback,
		Routes:          map[string]CompiledRoute{},
	}
	for _, in := range pol.Intents {
		d := Resolve(reg, sc, pol, in)
		r := CompiledRoute{
			Model:          d.Model,
			TaskType:       d.TaskType,
			Objective:      d.Objective,
			ConstraintsMet: d.ConstraintsMet,
			Reason:         d.Reason,
		}
		if d.Chosen != nil {
			r.Accuracy = d.Chosen.Accuracy
			r.CostUSD = d.Chosen.CostUSD
			r.LatencyMs = d.Chosen.LatencyMs
		}
		out.Routes[in.Name] = r
	}
	return out
}

// WriteCompiled marshals a CompiledRouting to path (creating parent dirs).
func WriteCompiled(path string, cr CompiledRouting) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(cr, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}
