package routing

import (
	"encoding/json"
	"os"
	"path/filepath"
	"time"
)

// CompiledRoutingVersion is the schema version of routing.json. Bump on a
// breaking change to the shape the sandbox reads.
//
// DO NOT BUMP IT FOR AN ADDITIVE FIELD. extensions/subagents.ts requires an
// EXACT match (`if (parsed.version !== ROUTING_SCHEMA) ... return null`) and
// silently drops every agent to "inherit parent model" when it does not match.
// Every sandbox image already built carries the old ROUTING_SCHEMA, so a tidy
// bump bricks subagent routing in the whole fleet until each image is rebuilt
// and reloaded. An optional field the sandbox reader ignores is not a breaking
// change; a bump ships WITH an image rebuild or not at all.
const CompiledRoutingVersion = 1

// CompiledRoute is one resolved intent the sandbox consumes: the chosen model
// plus the rationale (kept for auditability — the sandbox only needs Model).
type CompiledRoute struct {
	Model          string  `json:"model"`
	TaskType       string  `json:"task_type"`
	Objective      string  `json:"objective"`
	ConstraintsMet bool    `json:"constraints_met"`
	Accuracy       float64 `json:"accuracy,omitempty"`
	CostUSD        float64 `json:"cost_usd,omitempty"`
	LatencyMs      float64 `json:"latency_ms,omitempty"`
	Reason         string  `json:"reason"`
	// Relaxed carries Decision.Relaxed to the sandbox and to machine readers of
	// routing.json: which hard-constraint classes this route had to surrender.
	// Additive and optional — see CompiledRoutingVersion.
	Relaxed []string `json:"relaxed,omitempty"`
}

// CompiledRouting is the file the sandbox reads (routing.json). It maps intent
// name -> resolved route. It is generated by `route compile`; the sandbox never
// runs the resolver itself (single source of truth on the host) and never calls
// the host at spawn time (no hang risk).
type CompiledRouting struct {
	Version         int                      `json:"version"`
	Generated       string                   `json:"generated"`
	Note            string                   `json:"note"`
	DefaultFallback string                   `json:"default_fallback"`
	Routes          map[string]CompiledRoute `json:"routes"`
}

const compiledNote = "Generated by `pix route compile`. Maps an agent/task INTENT to the model the resolver chose from the current registry + scorecard. The sandbox (subagents.ts) reads routes[intent].model. Do not hand-edit — re-run compile after changing models.json / scorecard.json / policy.json (scorecard.json is hand-maintained; edit it directly, then re-run compile)."

// Compile resolves every intent in the policy and returns the routing.json
// payload. now is injected so the output is reproducible in tests.
func Compile(reg *Registry, sc *Scorecard, pol *Policy, now time.Time) CompiledRouting {
	out := CompiledRouting{
		Version:         CompiledRoutingVersion,
		Generated:       now.UTC().Format(time.RFC3339),
		Note:            compiledNote,
		DefaultFallback: pol.DefaultFallback,
		Routes:          map[string]CompiledRoute{},
	}
	for _, in := range pol.Intents {
		d := Resolve(reg, sc, pol, in)
		r := CompiledRoute{
			Model:          d.Model,
			TaskType:       d.TaskType,
			Objective:      d.Objective,
			ConstraintsMet: d.ConstraintsMet,
			Reason:         d.Reason,
			Relaxed:        d.Relaxed,
		}
		if d.Chosen != nil {
			r.Accuracy = d.Chosen.Accuracy
			r.CostUSD = d.Chosen.CostUSD
			r.LatencyMs = d.Chosen.LatencyMs
		}
		out.Routes[in.Name] = r
	}
	return out
}

// MaterializeBindings rewrites canonical catalog ids in a compiled route map
// to the provider/model ids Pi will use for concrete backends. Native bindings
// may deliberately preserve the canonical id; gateway bindings normally use
// <backend>/<upstream-id>. A route without a proven binding is removed rather
// than left pointing at an unreachable theoretical model.
func MaterializeBindings(in CompiledRouting, bindings []Binding, exclusiveBackend string) CompiledRouting {
	byModel := map[string]Binding{}
	for _, b := range bindings {
		if !b.Available || (exclusiveBackend != "" && b.Backend != exclusiveBackend) {
			continue
		}
		if _, exists := byModel[b.Model]; !exists {
			byModel[b.Model] = b
		}
	}
	for name, route := range in.Routes {
		b, ok := byModel[route.Model]
		if !ok {
			delete(in.Routes, name)
			continue
		}
		if b.UpstreamID == "" {
			b.UpstreamID = b.Model
		}
		if IsQualifiedID(b.UpstreamID) && b.Backend == providerOf(b.UpstreamID) {
			route.Model = b.UpstreamID
		} else {
			route.Model = b.Backend + "/" + b.UpstreamID
		}
		route.Reason += "; backend=" + b.Backend
		in.Routes[name] = route
	}
	return in
}

func providerOf(id string) string {
	for i := 0; i < len(id); i++ {
		if id[i] == '/' {
			return id[:i]
		}
	}
	return ""
}

// WriteCompiled marshals a CompiledRouting to path (creating parent dirs).
func WriteCompiled(path string, cr CompiledRouting) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(cr, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}
