// Package release is the Pix v2 release-manifest schema: one document
// binding a Pix version to the pix-agent image digest, the pix-memory image
// digest, the runtime archive digest, and the pinned strict kit revision
// (docs/design/pix-v2-architecture.md §3, §12).
//
// "Setup and doctor read that one manifest; there is no separately
// maintained version map." This package is exactly that one manifest's
// schema, parser, and validation, plus the on-disk location of the
// currently-installed record. It takes no dependency on pixhome (or
// anything else): every function that needs a Pix home root takes it as a
// plain string parameter, so this package stays usable from anything that
// already has one in hand.
package release

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
)

// Manifest binds one Pix release to the immutable identity of every artifact
// that must move together. Every field is required; Parse and Validate
// refuse a manifest missing or malforming one.
type Manifest struct {
	// Version is the Pix release version this manifest describes (e.g.
	// "2.0.0").
	Version string `json:"version"`

	// PixAgentDigest is the immutable OCI digest of the pix-agent image
	// (the DHI Node/Debian sandbox image) this release pins.
	PixAgentDigest string `json:"pix_agent_digest"`

	// PixMemoryDigest is the immutable OCI digest of the pix-memory image
	// (the DHI Go-built memory MCP image) this release pins.
	PixMemoryDigest string `json:"pix_memory_digest"`

	// RuntimeDigest is the content digest of the runtime archive: shipped
	// skills, agents, Pi settings, keybindings, and themes. It uses the same
	// "sha256:<hex>" shape as the image digests even though the archive is
	// not an OCI image, because it is the same immutable-content-identity
	// contract.
	RuntimeDigest string `json:"runtime_digest"`

	// KitRevision is the pinned strict Pix kit's revision identity.
	KitRevision string `json:"kit_revision"`
}

// digestRE matches an immutable content digest: "sha256:" followed by
// exactly 64 lowercase hex characters. A convenience tag (":latest", a
// branch name, anything mutable) is never a valid digest here — architecture
// §3 and §12 are explicit that "published references are immutable digests;
// convenience tags are not launch identity."
var digestRE = regexp.MustCompile(`^sha256:[0-9a-f]{64}$`)

// versionRE is the safe filename/release grammar Version must match:
// conservative and semver-compatible ([A-Za-z0-9][A-Za-z0-9._-]*) but never
// permissive enough to be a path. Version flows, UNQUOTED, straight into a
// filesystem path (release.RuntimeDir joins it under "runtime/", install.go
// names a tar prefix "runtime/"+version and a staging-dir suffix from it)
// with no separate sanitization at that boundary — this is the ONE gate.
// The charset alone already excludes '/', '\\', and every control byte
// (defense in depth: no slash, no backslash, no control characters); the
// required leading alnum additionally refuses a bare "." or a leading-dot
// token, and validateVersion below refuses an embedded ".." a dotted,
// semver-shaped string could otherwise still spell (e.g. "1.0...").
var versionRE = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`)

// validateVersion reports whether v is safe to use, unquoted, as both a
// single path segment (RuntimeDir's `runtime/<version>`) and a tar-entry
// prefix (extractRuntimeArchive's `runtime/<version>/`). Restriction: no
// slash, no backslash, no dot-segment (".", "..", or an embedded ".."),
// and no control character — a conservative, semver-compatible
// [A-Za-z0-9][A-Za-z0-9._-]* grammar, never the full Unicode/ARBITRARY-byte
// range JSON strings otherwise allow.
func validateVersion(v string) error {
	if strings.TrimSpace(v) == "" {
		return fmt.Errorf("version is required")
	}
	if !versionRE.MatchString(v) {
		return fmt.Errorf("version must match the safe release grammar [A-Za-z0-9][A-Za-z0-9._-]*, got %q", v)
	}
	if strings.Contains(v, "..") {
		return fmt.Errorf("version must not contain a %q dot-segment, got %q", "..", v)
	}
	return nil
}

// Validate reports every problem with m at once, rather than stopping at the
// first: a manifest is almost always hand-assembled or generated by release
// CI, and seeing every missing/malformed field in one error saves a
// fix-rerun-fix loop.
func (m Manifest) Validate() error {
	var problems []string

	if err := validateVersion(m.Version); err != nil {
		problems = append(problems, err.Error())
	}
	if err := validateDigest("pix_agent_digest", m.PixAgentDigest); err != nil {
		problems = append(problems, err.Error())
	}
	if err := validateDigest("pix_memory_digest", m.PixMemoryDigest); err != nil {
		problems = append(problems, err.Error())
	}
	if err := validateDigest("runtime_digest", m.RuntimeDigest); err != nil {
		problems = append(problems, err.Error())
	}
	if strings.TrimSpace(m.KitRevision) == "" {
		problems = append(problems, "kit_revision is required")
	}

	if len(problems) > 0 {
		return fmt.Errorf("invalid release manifest: %s", strings.Join(problems, "; "))
	}
	return nil
}

func validateDigest(field, value string) error {
	if !digestRE.MatchString(value) {
		return fmt.Errorf("%s must be an immutable digest matching sha256:<64 hex chars>, got %q", field, value)
	}
	return nil
}

// Parse decodes and validates a release manifest document. An unrecognized
// field is refused rather than silently ignored: a release manifest is
// machine-generated and consumed by setup/doctor gating, so a typo or a
// stale generator producing an extra key must fail loudly, not be dropped.
func Parse(data []byte) (*Manifest, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var m Manifest
	if err := dec.Decode(&m); err != nil {
		return nil, fmt.Errorf("parse release manifest: %w", err)
	}
	if dec.More() {
		return nil, fmt.Errorf("parse release manifest: trailing data after the document")
	}
	if err := m.Validate(); err != nil {
		return nil, err
	}
	return &m, nil
}

// Encode validates and renders m as canonical, indented JSON with a trailing
// newline. It refuses to encode an invalid manifest, so nothing this package
// writes to disk can fail Parse when read back.
func (m Manifest) Encode() ([]byte, error) {
	if err := m.Validate(); err != nil {
		return nil, err
	}
	buf, err := json.MarshalIndent(&m, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(buf, '\n'), nil
}
