// Runtime inference backends generated by the host. The manifest contains only
// public endpoint/model metadata; credential values remain proxy-managed or in
// process environment variables. Missing/malformed files are a clean no-op so
// this extension can never break pi startup.

import * as fs from "node:fs";
import * as path from "node:path";
import { getAgentDir } from "@earendil-works/pi-coding-agent";

type Backend = {
	driver: "native" | "openai-compatible" | "ollama";
	protocol?: "openai-completions" | "openai-responses" | "anthropic-messages" | "google-generative-ai";
	base_url?: string;
	auth: "1password" | "sbx-session" | "none";
	key_env?: string;
};

type Model = {
	id: string;
	catalog_model: string;
	backend: string;
	name: string;
	context_window: number;
	max_tokens: number;
	reasoning?: boolean;
	adaptive_thinking?: boolean;
	input_cost?: number;
	output_cost?: number;
};

type Manifest = { version: 1; backends: Record<string, Backend>; models: Model[] };

// Pi's default OpenAI Responses affinity mode adds a `session_id` HTTP
// header. Some standards-compliant gateways reject underscore-bearing header
// names at their edge before the request reaches the API. The hyphenated
// x-client-request-id header remains, so generated gateway providers use Pi's
// explicit no-session-header compatibility mode. Native OpenAI is untouched.
export function compatForBackend(backend: Backend): { sessionAffinityFormat: "openai-nosession" } | undefined {
	if (backend.protocol !== "openai-responses") return undefined;
	return { sessionAffinityFormat: "openai-nosession" };
}

export function compatForModel(
	backend: Backend,
	model: Model,
): { sessionAffinityFormat?: "openai-nosession"; forceAdaptiveThinking?: boolean } | undefined {
	const compat: { sessionAffinityFormat?: "openai-nosession"; forceAdaptiveThinking?: boolean } =
		compatForBackend(backend) ?? {};
	if (backend.protocol === "anthropic-messages" && model.adaptive_thinking) {
		compat.forceAdaptiveThinking = true;
	}
	return Object.keys(compat).length > 0 ? compat : undefined;
}

// Pi's Anthropic transport uses the Anthropic SDK, which appends
// `/v1/messages` to the configured base URL. Accept the common gateway form
// ending in `/v1`, but remove that suffix before handing it to the SDK so the
// request does not become `/v1/v1/messages`. Other protocols own their full
// API base and must remain byte-for-byte unchanged.
export function providerBaseURL(backend: Backend): string | undefined {
	const baseURL = backend.base_url?.trim();
	if (!baseURL) return undefined;
	if (backend.protocol === "anthropic-messages") return baseURL.replace(/\/v1\/?$/, "");
	return baseURL;
}

// Context accounting controls both the status denominator and Pi's automatic
// compaction threshold. Never invent limits here: the host compiles them from
// the model catalog. A malformed generated entry is omitted instead of being
// registered with a plausible-looking but unsafe default.
export function hasValidLimits(model: Model): boolean {
	return Number.isSafeInteger(model.context_window) && model.context_window > 0
		&& Number.isSafeInteger(model.max_tokens) && model.max_tokens > 0
		&& model.max_tokens <= model.context_window;
}

function readManifest(): Manifest | undefined {
	const manifestPath = path.join(getAgentDir(), "inference.json");
	let raw: string;
	try {
		raw = fs.readFileSync(manifestPath, "utf8");
	} catch {
		// Absent is the expected no-op path (no inference configured, or a
		// stack that never runs the host launcher) — silent by design.
		return undefined;
	}
	// From here the file EXISTS: a launcher ran and meant to hand this
	// extension something. Malformed/wrong-shape is never silent past this
	// point — it is exactly the failure mode that let the "json" vs.
	// "inference.json" filename bug ship unnoticed (present file, nothing
	// read it, fallback Anthropic 401 with no signal pointing here).
	try {
		const parsed = JSON.parse(raw);
		if (parsed?.version !== 1 || typeof parsed.backends !== "object" || !Array.isArray(parsed.models)) {
			process.stderr.write(
				`[inference] ${manifestPath} is present but is not a v1 manifest (backends/models); ignoring it and registering no generated providers\n`,
			);
			return undefined;
		}
		return parsed as Manifest;
	} catch (err) {
		process.stderr.write(`[inference] ${manifestPath} is present but failed to parse as JSON: ${err}\n`);
		return undefined;
	}
}

// The base kit exposes proxy-managed sentinel env vars for native providers.
// An exclusive custom-gateway runtime has no corresponding native credential,
// but third-party extensions can mistake the sentinel for a usable direct API
// key and send it to a public API. Hide only sentinels, and only for native
// backends absent from this runtime.
export function suppressUnusedDirectCredentialSentinels(manifest: Manifest): void {
	const nativeEnvs = new Set(
		Object.values(manifest.backends)
			.filter((backend) => backend.driver === "native" && backend.key_env)
			.map((backend) => backend.key_env as string),
	);
	for (const envName of ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY"]) {
		if (!nativeEnvs.has(envName) && process.env[envName] === "proxy-managed") {
			delete process.env[envName];
		}
	}
}

export default function (pi: any): void {
	const manifest = readManifest();
	if (!manifest) return;
	suppressUnusedDirectCredentialSentinels(manifest);
	for (const [name, backend] of Object.entries(manifest.backends)) {
		if (backend.driver === "native") continue;
		const models = manifest.models.filter((m) => m.backend === name && hasValidLimits(m));
		const baseURL = providerBaseURL(backend);
		if (!baseURL || models.length === 0) continue;
		let apiKey = "unused";
		if (backend.auth === "sbx-session") apiKey = "proxy-managed";
		if (backend.auth === "1password" && backend.key_env) apiKey = process.env[backend.key_env] ?? "proxy-managed";
		try {
			pi.registerProvider(name, {
				name,
				baseUrl: baseURL,
				api: backend.protocol ?? "openai-completions",
				apiKey,
				models: models.map((m) => ({
					id: m.id.startsWith(`${name}/`) ? m.id.slice(name.length + 1) : m.id,
					name: m.name || m.catalog_model,
					reasoning: m.reasoning ?? true,
					input: ["text"],
					cost: {
						input: m.input_cost ?? 0,
						output: m.output_cost ?? 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
					contextWindow: m.context_window,
					maxTokens: m.max_tokens,
					compat: compatForModel(backend, m),
				})),
			});
		} catch {
			/* best-effort; a generated backend must not break agent startup */
		}
	}
}
