// Runtime inference backends generated by the host. The manifest contains only
// public endpoint/model metadata; credential values remain proxy-managed or in
// process environment variables. Missing/malformed files are a clean no-op so
// this extension can never break pi startup.

import * as fs from "node:fs";
import * as path from "node:path";
import { getAgentDir } from "@earendil-works/pi-coding-agent";

type Backend = {
	driver: "native" | "openai-compatible" | "ollama";
	protocol?: "openai-completions" | "openai-responses" | "anthropic-messages" | "google-generative-ai";
	base_url?: string;
	auth: "1password" | "sbx-session" | "none";
	key_env?: string;
};

type Model = {
	id: string;
	catalog_model: string;
	backend: string;
	name: string;
	context_window?: number;
	max_tokens?: number;
	reasoning?: boolean;
	input_cost?: number;
	output_cost?: number;
};

type Manifest = { version: 1; backends: Record<string, Backend>; models: Model[] };

function readManifest(): Manifest | undefined {
	try {
		const parsed = JSON.parse(fs.readFileSync(path.join(getAgentDir(), "inference.json"), "utf8"));
		if (parsed?.version !== 1 || typeof parsed.backends !== "object" || !Array.isArray(parsed.models)) return undefined;
		return parsed as Manifest;
	} catch {
		return undefined;
	}
}

export default function (pi: any): void {
	const manifest = readManifest();
	if (!manifest) return;
	for (const [name, backend] of Object.entries(manifest.backends)) {
		if (backend.driver === "native") continue;
		const models = manifest.models.filter((m) => m.backend === name);
		if (!backend.base_url || models.length === 0) continue;
		let apiKey = "unused";
		if (backend.auth === "sbx-session") apiKey = "proxy-managed";
		if (backend.auth === "1password" && backend.key_env) apiKey = process.env[backend.key_env] ?? "proxy-managed";
		try {
			pi.registerProvider(name, {
				name,
				baseUrl: backend.base_url,
				api: backend.protocol ?? "openai-completions",
				apiKey,
				models: models.map((m) => ({
					id: m.id.startsWith(`${name}/`) ? m.id.slice(name.length + 1) : m.id,
					name: m.name || m.catalog_model,
					reasoning: m.reasoning ?? true,
					input: ["text"],
					cost: {
						input: m.input_cost ?? 0,
						output: m.output_cost ?? 0,
						cacheRead: 0,
						cacheWrite: 0,
					},
					contextWindow: m.context_window ?? 131072,
					maxTokens: m.max_tokens ?? 32768,
				})),
			});
		} catch {
			/* best-effort; a generated backend must not break agent startup */
		}
	}
}
