package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const pixGitExcludeBlock = `# Pix workspace state (generated by pix run)
**/.pix/*
!**/.pix/knowledge
`

// ensurePixGitExclude keeps Pix's machine-local workspace state out of git
// without changing the repository's tracked .gitignore. Git's per-repository
// info/exclude file is the right scope: every repository Pix touches gets the
// rule, while the optional .pix/knowledge pointer remains trackable.
func ensurePixGitExclude(workspace string) (bool, error) {
	cmd := exec.Command("git", "-C", workspace, "rev-parse", "--git-path", "info/exclude")
	out, err := cmd.Output()
	if err != nil {
		// A non-git workspace has no status to clean up. pix can still launch it.
		return false, nil
	}

	excludePath := strings.TrimSpace(string(out))
	if excludePath == "" {
		return false, nil
	}
	if !filepath.IsAbs(excludePath) {
		excludePath = filepath.Join(workspace, excludePath)
	}

	current, err := os.ReadFile(excludePath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read %s: %w", excludePath, err)
	}
	if strings.Contains(string(current), pixGitExcludeBlock) {
		return false, nil
	}

	if info, lerr := os.Lstat(excludePath); lerr == nil && info.Mode()&os.ModeSymlink != 0 {
		return false, fmt.Errorf("refusing to replace symlink %s", excludePath)
	}
	if err := os.MkdirAll(filepath.Dir(excludePath), 0o700); err != nil {
		return false, fmt.Errorf("create git exclude directory: %w", err)
	}

	prefix := ""
	if len(current) > 0 && current[len(current)-1] != '\n' {
		prefix = "\n"
	}
	if len(current) > 0 {
		prefix += "\n"
	}
	// Append rather than truncate-and-rewrite. Concurrent pix runs may both add
	// the idempotent block, but neither can erase a user's existing excludes.
	f, err := os.OpenFile(excludePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return false, fmt.Errorf("open %s: %w", excludePath, err)
	}
	if _, err := f.WriteString(prefix + pixGitExcludeBlock); err != nil {
		_ = f.Close()
		return false, fmt.Errorf("append %s: %w", excludePath, err)
	}
	if err := f.Close(); err != nil {
		return false, fmt.Errorf("close %s: %w", excludePath, err)
	}
	return true, nil
}
