// setup_cmd.go — `pix setup` as a typed root child (docs/design/
// pix-v2-surface.md §3.6, pix-v2-architecture.md §12). It is the whole of
// the v2 setup surface this launcher owns: idempotently initialize
// PIX_HOME, record the installed release manifest, reconcile the one named
// pix-memory container, and register/verify its reserved sbx MCP name —
// using real adapters (os/exec git, real Docker, a real HTTP prober, a real
// `sbx mcp` registrar). Nothing else runs here: no pack, no MCP allowlist,
// no model-provider interview, and no sandbox handoff. `pix doctor` reports
// the rest, and `pix run` starts a session.
package main

import (
	"fmt"

	"pix/host/cli"
	"pix/host/config"
	"pix/host/container"
	"pix/host/envsetup"
	"pix/host/pixhome"
	"pix/host/release"
	"pix/host/secret"
	nativeenv "pix/host/workflow/env"
	"pix/host/workflow/launch"
	"pix/host/workflow/provision"
	"pix/host/workspace"
)

// setupSeams is every external effect `pix setup` reaches for. Production
// fills it from productionSetupSeams(); a test substitutes doubles and
// drives the SAME Run body, so what is proven is the command's own
// sequencing (discover -> verify -> install -> record -> images -> env ->
// container -> MCP), not a parallel re-implementation of it.
type setupSeams struct {
	// DiscoverBundle finds the installed release bundle adjacent to this
	// binary. It is the one seam that must run BEFORE any Docker or
	// Gateway mutation: an incomplete installation is a refusal, not a
	// half-provisioned host.
	DiscoverBundle  func() (*release.Bundle, error)
	Prereqs         provision.PrereqChecker
	ContainerRunner container.Runner
	Prober          container.Prober
	MCP             provision.MCPRegistrar
}

func productionSetupSeams() setupSeams {
	return setupSeams{
		DiscoverBundle:  func() (*release.Bundle, error) { return release.DiscoverBundle(release.DefaultLocator) },
		Prereqs:         execChecker{},
		ContainerRunner: container.DefaultRunner,
		Prober:          httpProber{},
		MCP:             sbxMemoryRegistrar{},
	}
}

func (c *setupCmd) Help() string { return provision.Description }

// setupCmd provisions PIX_HOME. It takes no workspace argument and performs
// no agent handoff: `pix run` is the only thing that starts a sandbox.
type setupCmd struct {
	Verbose bool   `help:"Show the pix-memory container and MCP registration detail, not just the summary."`
	Env     string `help:"Also set up one existing environment: validate its declared requirements (docs/design/pix-v2-surface.md §3.6 step 7) and, if untrusted, run the same trust review pix env trust NAME does. It does not select that environment as the default."`
}

func (c *setupCmd) Run(d *cli.Deps) error { return c.run(d, productionSetupSeams()) }

func (c *setupCmd) run(d *cli.Deps, s setupSeams) error {
	home, err := pixhome.Resolve()
	if err != nil {
		return err
	}

	// The release bundle is resolved FIRST, from beside the resolved
	// executable (symlinks followed, so the `make install` shape
	// ~/.local/bin/pix -> out/pix finds out/'s manifest and archive). A
	// missing, unparseable, or digest-mismatched bundle fails here with the
	// exact install remedy, before Docker or the Gateway is touched: the
	// pinned image digests and the strict kit identity every later step
	// needs come from this one document (architecture §3, §12).
	bundle, err := s.DiscoverBundle()
	if err != nil {
		return fmt.Errorf("pix setup: %w", err)
	}
	if err := bundle.VerifyArchive(); err != nil {
		return fmt.Errorf("pix setup: %w", err)
	}
	// The pix-memory bearer token is generated by provision.Setup INSIDE the
	// setup lock, before the container spec's AuthTokenFile mount is used
	// (`docker create -v <path>:...:ro` fails outright if that file does not
	// exist yet, and the token is never a literal `-e`/`--env-file` argument
	// — either would land it in the container's own Config.Env, which
	// `docker inspect` exposes to anything on this host with inspect
	// access). Nothing here holds a copy of it.
	//
	// The container spec is derived from the DISCOVERED manifest, not from
	// whatever release.json a previous run happened to leave behind: the
	// image this setup reconciles is the one this binary shipped with.
	spec := homeContainerSpec(home)
	spec.Image = provision.MemoryImageRef(bundle.Manifest)
	res, err := provision.Setup(provision.Deps{
		Home:            home,
		Prereqs:         s.Prereqs,
		Manifest:        bundle.Manifest,
		Bundle:          bundle,
		ContainerRunner: s.ContainerRunner,
		Prober:          s.Prober,
		ContainerSpec:   spec,
		ConfirmReplace:  confirmContainerReplace(d),
		MCP:             s.MCP,
		EnsureImages: func(m release.Manifest) error {
			return provision.EnsureImages(s.ContainerRunner, m)
		},
	})
	if err != nil {
		return err
	}
	renderSetupResult(d, home, res, c.Verbose)
	setupCredentials(d)
	if c.Env != "" {
		if eerr := setupSelectedEnvironment(d, home, c.Env); eerr != nil {
			return eerr
		}
	}
	if !res.Ready() {
		return cli.SilentError{Code: 1}
	}
	return nil
}

// setupCredentials is setup's credential step, and it is deliberately small:
// establish THIS PIX_HOME's refs file, and offer to fill it when there is
// someone to ask. It never inspects, writes or repairs a host-global sbx
// secret — a global belongs to whoever pushed it, Pix reads only its own refs,
// and the values themselves are resolved per sandbox at launch. So a host
// covered in globals still gets its own refs file and still gets offered the
// 1Password prompt: inheriting another stack's credentials is not setup
// finishing early, it is setup never having run.
//
// It claims nothing about a model being ready. Nothing here resolved a ref,
// so the honest close is the command that configures one.
func setupCredentials(d *cli.Deps) {
	path, created, err := config.SeedOpRefs()
	if err != nil {
		fmt.Fprintf(d.Err, "pix setup: could not create the secrets file (%s): %v\n", path, err)
		return
	}
	if created {
		fmt.Fprintf(d.Out, "pix setup: created %s (op:// references only; no secret is ever stored there)\n", path)
	} else {
		fmt.Fprintf(d.Out, "pix setup: secrets file present at %s\n", path)
	}
	env := defaultShellEnv()
	if d.Interactive {
		// Fires only when op is installed AND no provider ref is configured
		// yet (OfferOnePasswordKeys' own gate) — never a nag, never a claim.
		secret.OfferOnePasswordKeys(env, d.In, d.Out, true)
	}
	if secret.ProviderKeyRefsPresent(env) {
		fmt.Fprintln(d.Out, "pix setup: model keys are configured as 1Password refs; each run resolves them into that run's own sandbox.")
		return
	}
	fmt.Fprintln(d.Out, "pix setup: no model provider key is configured yet. Next:")
	fmt.Fprintln(d.Out, "  pix secret set ANTHROPIC_API_KEY op://vault/item/field   (repeat per provider)")
	fmt.Fprintln(d.Out, "  pix secret check                                          (resolve every ref through op; no values printed)")
}

// setupSelectedEnvironment is `--env NAME`'s whole job (surface §3.6): sets
// up ONE EXISTING environment in addition to the machine-level
// prerequisites Run already handled above, and never selects it as the
// default (that is `pix env default NAME`'s job alone). It performs the
// same complete, default-No trust review `pix env trust NAME` does before
// checking anything else — an untrusted environment on a non-interactive
// terminal refuses here, naming that exact command, rather than silently
// skipping the review — then validates what this environment itself
// declares: its [inference.*] backends parse to a supported driver, and
// every roster reference ([models].main, each [agents] entry) resolves to
// a model machine config or this environment's own [[inference.models]]
// actually defines. Nothing here mutates config.toml or installs anything;
// a real reachability probe of a declared backend is `pix doctor`'s job
// (its own read-only probe set), not setup's.
func setupSelectedEnvironment(d *cli.Deps, home pixhome.Paths, name string) error {
	sel, err := nativeenv.ResolveIn(home, name)
	if err != nil {
		return envRun(d, err)
	}
	if terr := runEnvTrust(d, home, name, false, false); terr != nil {
		return terr
	}
	// ONE snapshot from here on. Everything below — the requirements check
	// AND any `[[setup]]` hook execution — reads this single in-memory
	// load, and the fingerprint proven accepted just below is the
	// fingerprint of THIS snapshot, never of a second, independently re-read
	// copy that could disagree with it.
	loaded, err := nativeenv.LoadHome(sel, nil, nil)
	if err != nil {
		return err
	}
	bom, fp, err := bomForLoaded(loaded)
	if err != nil {
		return err
	}
	if !trustAcceptedForFingerprint(home, sel, fp) {
		// runEnvTrust accepted SOMETHING and this snapshot is not it: the
		// environment changed under us between review and use. Fail closed.
		return fmt.Errorf("pix setup --env %s: the environment changed after its trust review; re-run: pix env trust %s", name, name)
	}
	cfg, _, err := workspace.LoadResolvedConfig()
	if err != nil {
		return err
	}
	if _, ierr := launch.EffectiveInferenceConfig(cfg, loaded.Sidecar); ierr != nil {
		return fmt.Errorf("pix setup --env %s: %w", name, ierr)
	}
	shipped, _, _ := listAgents()
	if verr := validateRunRoster(cfg, launch.EnvSelection{Name: loaded.Name, Root: loaded.Root, Sidecar: loaded.Sidecar}, shipped); verr != nil {
		return fmt.Errorf("pix setup --env %s: %v", name, verr)
	}
	fmt.Fprintf(d.Out, "pix setup: environment %q declared requirements check passed.\n", name)
	return runSetupHooks(d, name, loaded.Root, bom)
}

// runSetupHooks executes this environment's own `[[setup]]` hooks — the v2
// replacement for a pack's install/auth hook (docs/reference.md §"Setup
// hooks"). It runs ONLY here: `pix setup --env NAME`, after the default-No
// trust review above accepted the exact executables, argv, kinds and
// required bits it is about to run. `pix run` and `pix doctor` never reach
// it, and nothing outside this environment's own directory can contribute
// a hook.
func runSetupHooks(d *cli.Deps, name, root string, bom nativeenv.BillOfMaterials) error {
	if len(bom.SetupHooks) == 0 {
		return nil
	}
	res, err := envsetup.Run(root, bom.SetupHooks, envsetup.Options{
		EnvName:     name,
		Out:         d.Out,
		Err:         d.Err,
		In:          d.In,
		Interactive: d.Interactive,
	})
	for _, o := range res.Outcomes {
		if o.State == envsetup.StateSkipped {
			fmt.Fprintf(d.Out, "pix setup: setup hook %s: skipped (%s)\n", o.ID, o.Detail)
		}
	}
	if err != nil {
		return err
	}
	fmt.Fprintf(d.Out, "pix setup: environment %q setup hooks: %d checked, all required hooks ready.\n", name, len(res.Outcomes))
	return nil
}

// renderSetupResult prints what Setup actually did. Always shown, not only
// under --verbose: setup is a rerunnable idempotent step and a silent
// success gives the user nothing to confirm against.
func renderSetupResult(d *cli.Deps, home pixhome.Paths, res provision.Result, verbose bool) {
	switch {
	case res.Init.CreatedHome:
		fmt.Fprintf(d.Out, "pix setup: initialized PIX_HOME at %s\n", home.Home)
	default:
		fmt.Fprintf(d.Out, "pix setup: PIX_HOME already initialized at %s\n", home.Home)
	}
	if res.ReleaseInstalled {
		verb := "already installed"
		if res.Runtime.Extracted {
			verb = "installed"
		}
		fmt.Fprintf(d.Out, "pix setup: runtime %s at %s (kit %s)\n", verb, res.Runtime.Dir, res.KitRevision)
	}
	if res.DefaultEnvCreated {
		fmt.Fprintf(d.Out, "pix setup: created the %s environment at %s (this host had none)\n",
			provision.DefaultEnvironmentName, home.EnvironmentDir(provision.DefaultEnvironmentName))
	}
	fmt.Fprintf(d.Out, "pix setup: pix-memory container: %s\n", res.Container.Action)
	switch {
	case !res.MCPRegistered:
		fmt.Fprintln(d.Out, "pix setup: pix-memory MCP registration: not attempted (no registrar wired)")
	case res.MCPState == provision.MCPRegistrationAdded:
		fmt.Fprintln(d.Out, "pix setup: pix-memory MCP registration: registered")
	case res.MCPState == provision.MCPRegistrationPresentVerified:
		fmt.Fprintln(d.Out, "pix setup: pix-memory MCP registration: already registered at this home's endpoint (read back and matched); left untouched")
	case res.MCPState == provision.MCPRegistrationPresentUnverified:
		// NOT "ok", and NOT "verified": nothing could read the existing
		// entry's URL, so this run proved nothing about what the sandbox
		// would reach through that name (safety invariant 12). Nothing was
		// overwritten or removed; the user gets the exact commands.
		name := res.MCPName
		if name == "" {
			name = "this home's pix-memory MCP name"
		}
		fmt.Fprintf(d.Out, "pix setup: pix-memory MCP registration: %s is already registered, and its endpoint could not be read on this host (`sbx mcp inspect %s` and `sbx mcp get %s` both failed); left untouched, nothing overwritten or removed\n", name, name, name)
		fmt.Fprintf(d.Out, "  Check it yourself, and if it is not this home's memory endpoint, remove it and rerun setup:\n    sbx mcp inspect %s\n    sbx mcp rm %s\n    pix setup\n", name, name)
	default:
		fmt.Fprintln(d.Out, "pix setup: pix-memory MCP registration: not attempted")
	}
	if verbose {
		fmt.Fprintf(d.Err, "pix setup: pix home %s: container %s\n", home.Home, res.Container.Action)
	}
	if res.Ready() {
		fmt.Fprintln(d.Out, "pix setup: ready. For the full host report: pix doctor")
		return
	}
	fmt.Fprintln(d.Out, "pix setup: not ready. Run `pix doctor` for the exact fix.")
}

// confirmContainerReplace is the exact prompt architecture §9.1 requires
// before a mismatched pix-memory container is stopped, removed, and
// recreated: show the drift, ask, default to declining on anything that
// cannot ask (non-interactive, no confirmation requested with --yes).
func confirmContainerReplace(d *cli.Deps) func(current container.Info, want container.Spec) bool {
	return func(current container.Info, want container.Spec) bool {
		fmt.Fprintf(d.Err, "pix setup: the running pix-memory container does not match the pinned release:\n")
		fmt.Fprintf(d.Err, "  running: %s (fingerprint %s)\n", current.Image, current.Fingerprint())
		fmt.Fprintf(d.Err, "  wanted:  %s (fingerprint %s)\n", want.Image, want.Fingerprint())
		if !d.Interactive {
			fmt.Fprintf(d.Err, "pix setup: refusing to replace it on a non-interactive terminal; rerun interactively or remove it yourself: docker rm -f %s\n", want.ContainerName)
			return false
		}
		fmt.Fprint(d.Err, "Replace it? Its /data volume is preserved either way. [y/N] ")
		var line string
		fmt.Fscanln(d.In, &line)
		return line == "y" || line == "Y"
	}
}
