// setup_cmd.go — `pix setup` as a typed root child (docs/design/
// pix-v2-surface.md §3.6, pix-v2-architecture.md §12). It is the whole of
// the v2 setup surface this launcher owns: idempotently initialize
// PIX_HOME, record the installed release manifest, reconcile the one named
// pix-memory container, and register/verify its reserved sbx MCP name —
// using real adapters (os/exec git, real Docker, a real HTTP prober, a real
// `sbx mcp` registrar). Nothing else runs here: no pack, no MCP allowlist,
// no model-provider interview, and no sandbox handoff. `pix doctor` reports
// the rest, and `pix run` starts a session.
package main

import (
	"fmt"

	"pix/host/cli"
	"pix/host/container"
	"pix/host/pixhome"
	"pix/host/release"
	"pix/host/workflow/provision"
)

// setupSeams is every external effect `pix setup` reaches for. Production
// fills it from productionSetupSeams(); a test substitutes doubles and
// drives the SAME Run body, so what is proven is the command's own
// sequencing (discover -> verify -> install -> record -> images -> env ->
// container -> MCP), not a parallel re-implementation of it.
type setupSeams struct {
	// DiscoverBundle finds the installed release bundle adjacent to this
	// binary. It is the one seam that must run BEFORE any Docker or
	// Gateway mutation: an incomplete installation is a refusal, not a
	// half-provisioned host.
	DiscoverBundle  func() (*release.Bundle, error)
	Prereqs         provision.PrereqChecker
	ContainerRunner container.Runner
	Prober          container.Prober
	MCP             provision.MCPRegistrar
}

func productionSetupSeams() setupSeams {
	return setupSeams{
		DiscoverBundle:  func() (*release.Bundle, error) { return release.DiscoverBundle(release.DefaultLocator) },
		Prereqs:         execChecker{},
		ContainerRunner: container.DefaultRunner,
		Prober:          httpProber{},
		MCP:             sbxMemoryRegistrar{},
	}
}

func (c *setupCmd) Help() string { return provision.Description }

// setupCmd provisions PIX_HOME. It takes no workspace argument and performs
// no agent handoff: `pix run` is the only thing that starts a sandbox.
type setupCmd struct {
	Verbose bool `help:"Show the pix-memory container and MCP registration detail, not just the summary."`
}

func (c *setupCmd) Run(d *cli.Deps) error { return c.run(d, productionSetupSeams()) }

func (c *setupCmd) run(d *cli.Deps, s setupSeams) error {
	home, err := pixhome.Resolve()
	if err != nil {
		return err
	}

	// The release bundle is resolved FIRST, from beside the resolved
	// executable (symlinks followed, so the `make install` shape
	// ~/.local/bin/pix -> out/pix finds out/'s manifest and archive). A
	// missing, unparseable, or digest-mismatched bundle fails here with the
	// exact install remedy, before Docker or the Gateway is touched: the
	// pinned image digests and the strict kit identity every later step
	// needs come from this one document (architecture §3, §12).
	bundle, err := s.DiscoverBundle()
	if err != nil {
		return fmt.Errorf("pix setup: %w", err)
	}
	if err := bundle.VerifyArchive(); err != nil {
		return fmt.Errorf("pix setup: %w", err)
	}
	// The pix-memory bearer token is generated by provision.Setup INSIDE the
	// setup lock, before the container spec's AuthTokenFile mount is used
	// (`docker create -v <path>:...:ro` fails outright if that file does not
	// exist yet, and the token is never a literal `-e`/`--env-file` argument
	// — either would land it in the container's own Config.Env, which
	// `docker inspect` exposes to anything on this host with inspect
	// access). Nothing here holds a copy of it.
	//
	// The container spec is derived from the DISCOVERED manifest, not from
	// whatever release.json a previous run happened to leave behind: the
	// image this setup reconciles is the one this binary shipped with.
	spec := homeContainerSpec(home)
	spec.Image = provision.MemoryImageRef(bundle.Manifest)
	res, err := provision.Setup(provision.Deps{
		Home:            home,
		Prereqs:         s.Prereqs,
		Manifest:        bundle.Manifest,
		Bundle:          bundle,
		ContainerRunner: s.ContainerRunner,
		Prober:          s.Prober,
		ContainerSpec:   spec,
		ConfirmReplace:  confirmContainerReplace(d),
		MCP:             s.MCP,
		EnsureImages: func(m release.Manifest) error {
			return provision.EnsureImages(s.ContainerRunner, m)
		},
	})
	if err != nil {
		return err
	}
	renderSetupResult(d, home, res, c.Verbose)
	if !res.Ready() {
		return cli.SilentError{Code: 1}
	}
	return nil
}

// renderSetupResult prints what Setup actually did. Always shown, not only
// under --verbose: setup is a rerunnable idempotent step and a silent
// success gives the user nothing to confirm against.
func renderSetupResult(d *cli.Deps, home pixhome.Paths, res provision.Result, verbose bool) {
	switch {
	case res.Init.CreatedHome:
		fmt.Fprintf(d.Out, "pix setup: initialized PIX_HOME at %s\n", home.Home)
	default:
		fmt.Fprintf(d.Out, "pix setup: PIX_HOME already initialized at %s\n", home.Home)
	}
	if res.ReleaseInstalled {
		verb := "already installed"
		if res.Runtime.Extracted {
			verb = "installed"
		}
		fmt.Fprintf(d.Out, "pix setup: runtime %s at %s (kit %s)\n", verb, res.Runtime.Dir, res.KitRevision)
	}
	if res.DefaultEnvCreated {
		fmt.Fprintf(d.Out, "pix setup: created the %s environment at %s (this host had none)\n",
			provision.DefaultEnvironmentName, home.EnvironmentDir(provision.DefaultEnvironmentName))
	}
	fmt.Fprintf(d.Out, "pix setup: pix-memory container: %s\n", res.Container.Action)
	switch {
	case !res.MCPRegistered:
		fmt.Fprintln(d.Out, "pix setup: pix-memory MCP registration: not attempted (no registrar wired)")
	case res.MCPState == provision.MCPRegistrationAdded:
		fmt.Fprintln(d.Out, "pix setup: pix-memory MCP registration: registered")
	case res.MCPState == provision.MCPRegistrationPresent:
		// NOT "ok", and NOT "verified": nothing probed the existing entry's
		// URL, and `sbx mcp ls` cannot show it (safety invariant 12).
		fmt.Fprintln(d.Out, "pix setup: pix-memory MCP registration: present (URL unverifiable from this host); left untouched")
	default:
		fmt.Fprintln(d.Out, "pix setup: pix-memory MCP registration: not attempted")
	}
	if verbose {
		fmt.Fprintf(d.Err, "pix setup: pix home %s: container %s\n", home.Home, res.Container.Action)
	}
	if res.Ready() {
		fmt.Fprintln(d.Out, "pix setup: ready. For the full host report: pix doctor")
		return
	}
	fmt.Fprintln(d.Out, "pix setup: not ready. Run `pix doctor` for the exact fix.")
}

// confirmContainerReplace is the exact prompt architecture §9.1 requires
// before a mismatched pix-memory container is stopped, removed, and
// recreated: show the drift, ask, default to declining on anything that
// cannot ask (non-interactive, no confirmation requested with --yes).
func confirmContainerReplace(d *cli.Deps) func(current container.Info, want container.Spec) bool {
	return func(current container.Info, want container.Spec) bool {
		fmt.Fprintf(d.Err, "pix setup: the running pix-memory container does not match the pinned release:\n")
		fmt.Fprintf(d.Err, "  running: %s (fingerprint %s)\n", current.Image, current.Fingerprint())
		fmt.Fprintf(d.Err, "  wanted:  %s (fingerprint %s)\n", want.Image, want.Fingerprint())
		if !d.Interactive {
			fmt.Fprintln(d.Err, "pix setup: refusing to replace it on a non-interactive terminal; rerun interactively or remove it yourself: docker rm -f pix-memory")
			return false
		}
		fmt.Fprint(d.Err, "Replace it? Its /data volume is preserved either way. [y/N] ")
		var line string
		fmt.Fscanln(d.In, &line)
		return line == "y" || line == "Y"
	}
}
