package monitor

// fixture_test.go proves this package's Decode/Store round-trip real,
// tap-produced NDJSON — the SAME fixture files
// tests/prefix-stability.test.mjs (TS) consumes, generated by
// scripts/dev/make-monitor-fixtures.mjs from extensions/monitor.ts's own
// summarizeRequest(). One fixture (session-append-only.ndjson) also
// carries a field ("summary.messageHashes") that is NOT part of the Go
// wire schema at all — see the generator's doc comment — which makes these
// files a real "unknown field" test, not a synthetic one: if Decode ever
// stopped tolerating an extra field, this test (not just the hand-built
// one in event_test.go) would catch it on the actual producer's output.
import (
	"os"
	"path/filepath"
	"testing"
)

func fixtureDir(t *testing.T) string {
	t.Helper()
	// services/host/monitor -> repo root is three levels up.
	dir, err := filepath.Abs(filepath.Join("..", "..", "..", "tests", "fixtures", "monitor"))
	if err != nil {
		t.Fatalf("resolve fixture dir: %v", err)
	}
	if _, err := os.Stat(dir); err != nil {
		t.Fatalf("fixture dir %s: %v (expected tests/fixtures/monitor to exist at the repo root)", dir, err)
	}
	return dir
}

func TestFixturesDecodeAndRoundTripThroughStore(t *testing.T) {
	dir := fixtureDir(t)
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read fixture dir: %v", err)
	}
	found := 0
	for _, ent := range entries {
		if ent.IsDir() || filepath.Ext(ent.Name()) != ".ndjson" {
			continue
		}
		found++
		t.Run(ent.Name(), func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(dir, ent.Name()))
			if err != nil {
				t.Fatalf("read %s: %v", ent.Name(), err)
			}
			lines := splitNDJSONLines(raw)
			if len(lines) == 0 {
				t.Fatalf("%s has no lines", ent.Name())
			}

			s := newTestStore(t, StoreConfig{})
			var sandboxID, sessionID string
			for i, line := range lines {
				ev, err := Decode(line)
				if err != nil {
					t.Fatalf("Decode line %d: %v\nline: %s", i, err, line)
				}
				if _, ok := ev.(UnknownEvent); ok {
					t.Fatalf("line %d decoded as UnknownEvent, want a recognized kind: %s", i, line)
				}
				env := ev.Envelope()
				sandboxID, sessionID = env.SandboxID, env.SessionID
				if err := s.Append(ev); err != nil {
					t.Fatalf("Append line %d: %v", i, err)
				}
			}

			got, err := s.Tail(sandboxID, sessionID, 0)
			if err != nil {
				t.Fatalf("Tail: %v", err)
			}
			if len(got) != len(lines) {
				t.Errorf("Tail() returned %d events, want %d (one per fixture line)", len(got), len(lines))
			}
		})
	}
	if found == 0 {
		t.Fatal("no .ndjson fixtures found — tests/fixtures/monitor is expected to be non-empty")
	}
}
