package monitor

// fixture_test.go round-trips real, tap-produced NDJSON — the SAME fixtures
// tests/prefix-stability.test.mjs consumes, generated by
// scripts/dev/make-monitor-fixtures.mjs from extensions/monitor.ts's own
// summarizeRequest(). One (session-append-only.ndjson) carries a field
// ("summary.messageHashes") that is NOT in the Go wire schema, which makes
// these files a real "unknown field" test on the actual producer's output,
// not a synthetic one.
import (
	"os"
	"path/filepath"
	"testing"
)

func TestFixturesDecodeAndRoundTripThroughStore(t *testing.T) {
	// services/host/monitor -> repo root is three levels up.
	dir := filepath.Join("..", "..", "..", "tests", "fixtures", "monitor")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read fixture dir %s: %v (expected it at the repo root)", dir, err)
	}
	found := 0
	for _, ent := range entries {
		if ent.IsDir() || filepath.Ext(ent.Name()) != ".ndjson" {
			continue
		}
		found++
		t.Run(ent.Name(), func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(dir, ent.Name()))
			if err != nil {
				t.Fatalf("read %s: %v", ent.Name(), err)
			}
			lines := splitLines(raw)
			if len(lines) == 0 {
				t.Fatalf("%s has no lines", ent.Name())
			}

			s := newTestStore(t, StoreConfig{})
			var sandboxID, sessionID string
			for i, line := range lines {
				ev, err := Decode(line)
				if err != nil {
					t.Fatalf("Decode line %d: %v\nline: %s", i, err, line)
				}
				if _, ok := ev.(UnknownEvent); ok {
					t.Fatalf("line %d decoded as UnknownEvent, want a recognized kind: %s", i, line)
				}
				env := ev.Envelope()
				sandboxID, sessionID = env.SandboxID, env.SessionID
				if err := s.Append(ev); err != nil {
					t.Fatalf("Append line %d: %v", i, err)
				}
			}

			got := mustTail(t, s, sandboxID, sessionID, 0)
			if len(got) != len(lines) {
				t.Errorf("Tail() returned %d events, want %d (one per fixture line)", len(got), len(lines))
			}
		})
	}
	if found == 0 {
		t.Fatal("no .ndjson fixtures found — tests/fixtures/monitor is expected to be non-empty")
	}
}
